name: Cypres with Cucumber end-to-end tests
on: [push]
permissions:
  contents: write
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: npm ci    
      - name: Install Dependencies
        run: npm install 
      - name: Cypress run
        uses: cypress-io/github-action@v4
      - name: Create report
        if: always()
        run: npm run generate
      - uses: actions/upload-artifact@v2
        if: always()
        with: 
          name: cucumber-reports
          path: ./reports/cucumber-htmlreport.html
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./reports/cucumber-htmlreport.html # The folder the action should deploy.
